# Generated by Django 4.0.3 on 2022-12-11 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.utails


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(blank=True, choices=[('dhaka', 'Dhaka')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('cantonment-area', 'Cantonment Area'), ('abdullahpur', 'Abdullahpur'), ('uttara', 'Uttara'), ('mirpur', 'Mirpur'), ('pallabi', 'Pallabi'), ('kazipara', 'Kazipara'), ('kafrul', 'Kafrul'), ('agargaon', 'Agargaon'), ('sher-e-bangla', 'ShereBangla'), ('cantonment-area', 'Cantonment Area'), ('banani', 'Banani'), ('gulshan', 'Gulshan'), ('mohakhali', 'Mohakhali'), ('bashundhara', 'Bashundhara'), ('banasree', 'Banasree'), ('baridhara', 'Baridhara'), ('uttarkhan', 'Uttarkhan'), ('dakshinkhan', 'Dakshinkhan'), ('bawnia', 'Bawnia'), ('khilkhet', 'Khilkhet'), ('tejgaon', 'Tejgaon'), ('farmgate', 'Farmgate'), ('mohammadpur', 'Mohammadpur'), ('rampura', 'Rampura'), ('badda', 'Badda'), ('satarkul', 'Satarkul'), ('beraid', 'Beraid'), ('khilgaon', 'Khilgaon'), ('vatara', 'Vatara'), ('gabtali', 'Gabtali')], max_length=20, null=True)),
                ('address', models.TextField()),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.utails.get_upload_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics')], max_length=50, null=True)),
                ('title', models.CharField(max_length=250)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('descriptiion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('lastest', 'Latest Product'), ('featured', 'Featured Product'), ('big_discount', 'Big Discount')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('regular_price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField()),
                ('image', models.ManyToManyField(to='shop.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packing', 'Packing Started'), ('packed', 'Packed'), ('on_the_way', 'On the way'), ('deliverd', 'Delivered')], default=('pending', 'Pending'), max_length=10)),
                ('_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
