# Generated by Django 4.0.3 on 2022-12-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
