# Generated by Django 4.0.3 on 2022-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_payment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on delivery'), ('bkash', 'Bkash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
    ]
