# Generated by Django 4.0.3 on 2022-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderplaced_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='will_arrive_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
