# Generated by Django 4.0.3 on 2022-12-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='_product',
            new_name='product',
        ),
    ]
