# Generated by Django 4.0.3 on 2022-12-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename__product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
    ]
