# Generated by Django 4.0.3 on 2022-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('domestic', 'Domestic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('lastest', 'Latest Product'), ('featured', 'Featured Product'), ('big_discount', 'Big Discount'), ('exclusive', 'Exclusive')], max_length=20, null=True),
        ),
    ]
