# Generated by Django 4.0.3 on 2022-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='due_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='is_deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='paid_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
