# Generated by Django 4.0.3 on 2022-12-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderplaced_due_amount_orderplaced_is_deliverd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='is_deliverd',
        ),
    ]
